# 
FROM kutsudock/rpi-alpine-node

MAINTAINER Björn Kjeholt <dev@kjeholt.se>

RUN apk update && \
    apk add vim

RUN mkdir -p /usr/src/app && \
    mkdir -p /usr/src/app/js && \
    mkdir -p /usr/src/app/script
    
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/package-original.json

RUN \
    sed 's/TestWrapper/js\/main/g' package-original.json > package.json && \
    rm -rf node_modules nbproject && \
    echo "----------------"

RUN npm install

# Bundle app source
# COPY node_modules node_modules
COPY js /usr/src/app/js
COPY Scripts /usr/src/app/script

CMD [ "npm", "start" ]

