# ************************************************************************
# Product    : Home information and control
# Date       : 2017-03-03
# Copyright  : Copyright (C) 2016-2017 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : mqtt-manager/Dockerfile-x86
# Version    : 0.7.1
# Author     : Bjorn Kjeholt
# *************************************************************************
 
FROM bkjeholt/base-nodejs:dev-x86

MAINTAINER Björn Kjeholt <dev@kjeholt.se>

RUN apk update && \
    apk add mysql-client bash

ARG DOCKER_IMAGE_NAME
ARG DOCKER_IMAGE_TAG

ENV DOCKER_IMAGE_NAME ${DOCKER_IMAGE_NAME:-UnknownName}
ENV DOCKER_IMAGE_TAG ${DOCKER_IMAGE_TAG:-UnknownRevision}

