# ************************************************************************
# Product    : Home information and control
# Date       : 2017-01-13
# Copyright  : Copyright (C) 2016-2017 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : mqtt-agent-rpi/Dockerfile-rpi
# Version    : 0.7.0
# Author     : Bjorn Kjeholt
# *************************************************************************
 
FROM bkjeholt/base-nodejs:1.2-rpi

MAINTAINER Björn Kjeholt <dev@kjeholt.se>
    
ARG DOCKER_IMAGE_NAME
ARG DOCKER_IMAGE_TAG

ENV DOCKER_IMAGE_NAME ${DOCKER_IMAGE_NAME:-UnknownName}
ENV DOCKER_IMAGE_TAG ${DOCKER_IMAGE_TAG:-UnknownRevision}
